import React, { useState } from 'react';
import { invoke } from '@tauri-apps/api/tauri';
import { Image, Loader2, Download } from 'lucide-react';

interface ImageGeneratorProps {
  apiKey: string;
}

const ImageGenerator: React.FC<ImageGeneratorProps> = ({ apiKey }) => {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generateImage = async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt');
      return;
    }

    setLoading(true);
    setError('');
    setImageUrl('');

    try {
      const url: string = await invoke('generate_image_minimax', {
        apiKey,
        prompt
      });
      setImageUrl(url);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate image');
      console.error('Image generation error:', err);
    } finally {
      setLoading(false);
    }
  };

  const downloadImage = async () => {
    if (!imageUrl) return;

    try {
      await invoke('download_image', {
        url: imageUrl,
        filename: `generated-image-${Date.now()}.png`
      });
      alert('Image downloaded successfully!');
    } catch (err) {
      console.error('Download error:', err);
      alert('Failed to download image');
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <div className="bg-card border border-border rounded-lg p-6">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
          <Image className="w-7 h-7 text-primary" />
          AI Image Generator
        </h2>

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-foreground mb-2">
              Describe the image you want to generate
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="w-full px-4 py-3 bg-muted border border-border rounded-lg text-white focus:ring-2 focus:ring-purple-500 min-h-[100px]"
              placeholder="e.g., A simple diagram showing the water cycle with labels, educational style, clean white background"
            />
          </div>

          <button
            onClick={generateImage}
            disabled={loading || !prompt.trim()}
            className="w-full px-6 py-3 bg-purple-600 hover:bg-purple-700 disabled:bg-muted/60 disabled:cursor-not-allowed text-white rounded-lg flex items-center justify-center gap-2 transition-colors"
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Generating Image...
              </>
            ) : (
              <>
                <Image className="w-5 h-5" />
                Generate Image
              </>
            )}
          </button>

          {error && (
            <div className="p-4 bg-red-900/50 border border-red-700 rounded-lg text-red-300">
              {error}
            </div>
          )}

          {imageUrl && (
            <div className="space-y-4">
              <div className="p-4 bg-green-900/50 border border-green-700 rounded-lg text-green-300">
                ✅ Image generated successfully!
              </div>

              <div className="relative">
                <img
                  src={imageUrl}
                  alt="Generated by AI"
                  className="w-full rounded-lg border border-border"
                />
                <button
                  onClick={downloadImage}
                  className="absolute top-4 right-4 p-2 bg-card hover:bg-muted text-white rounded-lg border border-border transition-colors"
                  title="Download image"
                >
                  <Download className="w-5 h-5" />
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ImageGenerator;
